blog/urls.py
from django.urls import path,include
from .import views
app_name = 'blog'
urlpatterns = [
    path('',views.blog,name = 'blog'),
    path('<int:blog_id>/',views.detail,name = 'detail'),
]

portfoilio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from personal import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name = 'home'),
    path('about/',views.about,name = 'about'),
    path('blog/',include('blog.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class Blog(models.Model):
    title = models.CharField(max_length = 200)
    dot = models.DateField()
    summary = RichTextUploadingField()
    def __str__(self):
        return self.title

personal/models.py
from django.db import models
class Project(models.Model):
    title = models.CharField(max_length = 100)
    image = models.ImageField(upload_to = 'images/')
    descriptionn = models.CharField(max_length = 250)
    url = models.URLField(blank = True)
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

def blog(request):
    r = Blog.objects.order_by('-dot')
    return render(request, 'blog/blog.html',{'blog':r})
def detail(request,blog_id):
    a = get_object_or_404 (Blog,pk = blog_id)
    return render(request,'blog/detail.html',{'blog':a})

personal/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    a = Project.objects.all()
    return render(request,'personal/home.html',{'data':a})
def about(request):
    return render(request,'personal/about.html')

blog/templates/blog/blog.html
{% extends 'personal/base.html' %}
{% block content %}
<h1 class = 'font-weight-bold text-center'>Blog</h1>
<h3 class = 'text-center mb-5'>Shyam has written {{blog.count}} blog{{blog.count|pluralize}}</h3>
{% for blog in blog.all %}
<div class='container'>
  <div class = 'row justify-content-center my-3'>
    <div class = 'col-md-10'>
      <a href = '{% url "blog:detail" blog.id %}' style = 'color:black'>
        <h1>{{blog.title}}</h1>
      </a>
      <h5 class = 'text-muted'><span class="oi oi-calendar"></span> {{ blog.dot|date:'M d Y' }}</h5>
      <h4>{{ blog.summary|striptags|truncatechars:150 }}</h4>
    </div>

  </div>
{% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'personal/base.html' %}
{% block content %}
<div class ='container'>
  <h1 class = 'text-center' id = 'blogtitle'>{{blog.title}}</h1>
  <h5 class = 'text-center text-muted md-5'><span class="oi oi-calendar"></span> {{ blog.dot|date:'F d Y'}}</h5>
</div>
<br/>
{{blog.summary.media}}
<p id='blogdes'>{{ blog.summary|safe }}</p>
{% endblock %}

personal/templates/personal/about.html
{% extends 'personal/base.html' %}
{% block content %}
<br/>
<style>
  #abt {
    font-family: 'Montserrat', sans-serif; !important;
  }
</style>
<div class ='container'>
  <h1 class = 'text-center' id = 'blogtitle'>About me</h1>
  <hr/>
</div>
<p id = 'abt'>I'm a Web and AI developer in love with photography, editing stuffs, programming and gaining knowledge. Check out my GitHub repositories for source codes of Django webs and Neural Networks. I'm a High School Student and I created this website using Django. I also have experiences in Photoshop, Premiere Pro, Python and HTML. Also you can stop and send a hello to my e-mail. </p>
<p>
        <a href="mailto:clashwithchiefrpjyt@gmail.com" class="btn btn-success my-2">Email me</a>
      </p>
{% endblock %}

personal/templates/personal/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href='{% static "open-iconic/font/css/open-iconic-bootstrap.css" %}' rel='stylesheet'>
  <link rel="icon" type = 'image/png' href="{% static 'profile pic 1.png' %}" >
  <link rel = 'stylesheet' href = '{% static "custom.css"  %}'>
  <link href="https://fonts.googleapis.com/css2?family=Oleo+Script+Swash+Caps&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Lato:ital@1&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
  <style>
  body {
    font-family: 'Lato', sans-serif;

  }

  .left, .right {
    float: left;
    width: 20%; /* The width is 20%, by default */
  }

  .main {
    float: left;
    width: 60%; /* The width is 60%, by default */
  }
  .carousel-item{
    height: 400px !important;
  }
  #carouselExampleIndicators li {
    width: 7px;
    height: 7px;
    border-radius: 75%;
  }
  .carousel-caption {
    right: 5%;
    text-align: right;
    max-width: 300px;
    left: auto;
    padding:5px;
}
  </style>
  <title>Shyam Sundhar</title>
</head>
<body>
  <div class = 'container' id = 'nav'>
    <nav class="navbar navbar-expand-lg navbar-light " style = 'color:white' id = 'topnav'>
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src = '{% static "profile pic 1.png" %}' height= 30 width=30 class="d-inline-block align-top">
        Shyam Sundhar
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class = 'navbar-nav ml-auto'>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'about' %}" >About me<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="https://github.com/ShyamSundhar1411" target = '_blank'>GitHub<span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" href="https://www.Youtube.com/c/gamingwithskytorrush" target = "_blank">YouTube</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'blog:blog' %}">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    <footer class="text-muted">
      <div class="row">
    <div class="col-md-6 text-right"><!--Start of Tawk.to Script-->
      <!--Start of Tawk.to Script-->
      <script type="text/javascript">
      var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
      (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/5fd727e5a8a254155ab3160d/1eu95drpc';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
      })();
</script>
<!--End of Tawk.to Script-->
<!--End of Tawk.to Script--></div>
    </div>
      <!--Start of Tawk.to Script-->
<!--End of Tawk.to Script-->
      <div class="container text-center">
        <p>© Shyam {% now "Y" %}</p>
      </footer>

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
    </html>

personal/templates/personal/home.html
{% extends 'personal/base.html' %}
{% load static %}
{% block content %}
<br/>
<br/>
<div id="carouselExampleIndicators" class="carousel slide img-fluid border border-dark" data-ride="carousel" data-interval ='500'>
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
  </ol>
  <div class="carousel-inner" height = 400 width = 400>
    <div class="carousel-item active">
      <img src="{% static 'Hey.jpg' %}" class="d-block w-100" width = 100 height = 500>
      <div class="carousel-caption d-none d-md-block">
        <p style = 'padding-left:5px;float: right;'id =#p2> - Image By Shyam</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'Flower 11.jpg' %}" class="d-block w-100 " width = 100 height = 500>
      <div class="carousel-caption d-none d-md-block">
        <p id="#p1"> - Image By Shyam</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'Flower 3.jpg' %}" class="d-block w-100 " width = 100 height = 500>
      <div class="carousel-caption d-none d-md-block">
        <p  id='#p2'> - Image By Shyam</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'shine.png' %}" class="d-block w-100 " width = 100 height = 500>
      <div class="carousel-caption d-none d-md-block">
        <p  id='#p2'> - Wallpaper By Shyam</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'way.png' %}" class="d-block w-100 " width = 100 height = 500>
      <div class="carousel-caption d-none d-md-block">
        <p id='#p2'> - Wallpaper By Shyam</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br/>
<br/>
<div class="container row justify-content-center " style = 'padding-left:40px;'>
  <img class='img-rounded 'style = '
  height:200px;
  width:200px;
  border-radius: 50%;'src = '{% static "65313257.png" %}' >
</div>
<div class = 'container text-center'>
  <div class="row justify-content-center mb-5">
    <div class="col-my-3 text-center">
      <h1 id="hometext" class = 'font-weight-bold float-left' ></h1>

    </div>
  </div>
</div>
<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row" >
  {% for i in data %}
  <div class="col-lg-4 col-md-6">

    {% if i.url %}
    <a href="{{ i.url }}" target = '_blank'>
      <img src="{{ i.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}
    <img src="{{ i.image.url }}" class="img-fluid mb-2">

    {% endif %}
    <br/>
    <h3>{{ i.title }}</h3>
    <p>{{ i.descriptionn }}</p>

  </div>
  {% endfor %}
</div>
<script>
var str = "<p>Hey, I am Shyam</p>",
i = 0,
isTag,
text;

(function type() {
  text = str.slice(0, ++i);
  if (text === str) return;

  document.getElementById('hometext').innerHTML = text;

  var char = text.slice(-1);
  if( char === '<' ) isTag = true;
  if( char === '>' ) isTag = false;

  if (isTag) return type();
  setTimeout(type, 80);
}());
</script>

{% endblock %}